nhnacademy-be7-heukbaekbook/heukbaekbook-shop

pom.xml, src/main/java/com/nhnacademy/heukbaekbookshop/category/domain/Category.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/domain/Contributor.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/domain/Customer.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/domain/Tag.java, src/main/resources/application.properties, src/main/resources/application.yml
- #8 
- 엔티티 관계 설정 중 발생한 충돌 문제 해결
-
=> [Fix] 엔티티 관계 충돌 해결 - #8

pom.xml, src/main/java/com/nhnacademy/heukbaekbookshop/common/config/SecurityConfig.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/domain/Customer.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/domain/Grade.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/domain/Member.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/dto/request/MemberCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/dto/response/MemberResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/repository/MemberRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/service/impl/MemberServiceImpl.java, src/main/resources/application.yml
- [FIX] #13 
- 회원, 고객 엔티티 수정, 회원가입 로직 수정
-
=> [Fix]회원 엔테티 상속관계, 회원가입 수정

src/main/java/com/nhnacademy/heukbaekbookshop/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/domain/Customer.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/domain/Member.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/dto/request/MemberUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/dto/response/MemberResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/exception/InvalidPasswordException.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/exception/MemberNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/repository/MemberRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/service/MemberService.java, src/main/java/com/nhnacademy/heukbaekbookshop/member/service/impl/MemberServiceImpl.java, src/test/java/com/nhnacademy/heukbaekbookshop/member/service/impl/MemberServiceTest.java
- close #14
- close #15 
- 회원 수정, 탈퇴 구현, 테스트 작성
=> [Feat] 회원 수정, 회원 탈퇴 구현, 테스트 작성

src/main/java/com/nhnacademy/heukbaekbookshop/category/repository/CategoryRepository.java
=> [Fix] 충돌 코드 손실 해결 - #38

src/main/java/com/nhnacademy/heukbaekbookshop/tag/controller/TagController.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/request/TagCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/request/TagUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/response/TagCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/response/TagDeleteResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/response/TagDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/response/TagUpdateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/exception/TagAlreadyExistsException.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/exception/TagNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/service/TagService.java, src/test/java/com/nhnacademy/heukbaekbookshop/tag/TagControllerTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/tag/TagServiceTest.java
- #42
- 도서 태그 crud 구현, 테스트 코드 작성
-
=> [Feat] 도서 태그 crud 구현, 테스트 코드 작성 - #42

src/main/java/com/nhnacademy/heukbaekbookshop/contributor/controller/PublisherController.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/request/PublisherCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/request/PublisherUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/PublisherCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/PublisherDeleteResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/PublisherDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/PublisherUpdateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/exception/PublisherAlreadyExistException.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/exception/PublisherNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/service/PublisherService.java, src/test/java/com/nhnacademy/heukbaekbookshop/publisher/PublisherControllerTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/publisher/PublisherServiceTest.java
- #45
- 출판사 등록, 수정, 삭제 구현 기능 및 테스트 코드 작성 
-
=> [Feat] 출판사 등록, 수정, 삭제 구현 기능 및 테스트 코드 작성 - #45

.github/workflows/maven.yml
=> udpate maven.yml

src/main/java/com/nhnacademy/heukbaekbookshop/contributor/controller/ContributorController.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/request/ContributorCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/request/ContributorUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/ContributorCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/ContributorDeleteResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/ContributorDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/ContributorUpdateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/exception/ContributorAlreadyExistException.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/exception/ContributorNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/repository/ContributorRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/service/ContributorService.java, src/test/java/com/nhnacademy/heukbaekbookshop/contributor/ContributorControllerTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/contributor/ContributorServiceTest.java
- #59
- 기여자 crud 구현, 테스트 코드 작성 완료
-
=> [Feat] 기여자 crud 구현, 테스트 코드 작성 완료 - #59

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/domain/Book.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookCartResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookSummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/like/LikeService.java, src/main/java/com/nhnacademy/heukbaekbookshop/common/advice/ErrorResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/common/advice/WebControllerAdvice.java, src/main/java/com/nhnacademy/heukbaekbookshop/common/formatter/BookFormatter.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/ContributorSummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/PublisherSummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/domain/BookImage.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/domain/Image.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/domain/ImageType.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/domain/ReviewImage.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/domain/WrappingPaperImage.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/exception/ImageNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/repository/BookImageRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/repository/ImageRepository.java, src/main/resources/application.yml, src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookServiceTest.java
- close #77 
- QueryDSL, 패치조인과 배치 사이즈 등을 활용하여 쿼리 성능 개선
-
=> [Refactor] 도서 조회 QueryDSL 적용

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookAdminController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/controller/CategoryController.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/dto/response/CategoryDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/repository/CategoryRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/service/CategoryService.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/controller/ContributorController.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/controller/PublisherController.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/ContributorDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/dto/response/PublisherDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/service/ContributorService.java, src/main/java/com/nhnacademy/heukbaekbookshop/contributor/service/PublisherService.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/controller/TagController.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/dto/response/TagDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/tag/service/TagService.java
- #79
- 카테고리, 기여자, 태그 전체 조회 구현
-
=> [Feat] 폼 구현 중 발생한 수정 사항

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java
=> [Fix] 도서 경로 수정 - #84

src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java
=> [Fix] 이미지 타입 insert 문제 해결 - #87

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java
=> [Chore] 3차 배포 수정 

src/main/java/com/nhnacademy/heukbaekbookshop/common/advice/WebControllerAdvice.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/domain/Member.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/request/MemberUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/exception/InvalidPasswordException.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java, src/test/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberServiceTest.java
Reverts nhnacademy-be7-heukbaekbook/heukbaekbook-shop#96
=> Revert "[Fix] 회원가입 시 중복확인 로직 수정"

src/main/java/com/nhnacademy/heukbaekbookshop/common/advice/WebControllerAdvice.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/controller/MemberAddressController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/dto/MemberAddressDto.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/service/MemberAddressService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/service/impl/MemberAddressServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/domain/Member.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/request/MemberUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/exception/InvalidPasswordException.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java, src/test/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberServiceTest.java
- close #95 
- 회원가입 시 중복 확인 로직 수정
-
=> [Fix] 회원가입 시 중복 확인 로직 수정

src/main/java/com/nhnacademy/heukbaekbookshop/point/controller/PointEarnStandardController.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/domain/PointEarnStandard.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/domain/PointEarnStandardStatus.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/domain/PointEarnTriggerEvent.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/domain/PointHistory.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/dto/mapper/PointEarnStandardMapper.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/dto/request/PointEarnStandardRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/dto/response/PointEarnStandardResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/exception/PointEarnStandardIdNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/repository/PointEarnStandardRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/service/PointEarnStandardService.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/service/impl/PointEarnStandardServiceImpl.java
- #102 
- 포인트 적립 기준 CRUD API
-
=> [Feat] 포인트 적립 기준 CRUD api 구현

src/main/java/com/nhnacademy/heukbaekbookshop/common/advice/WebControllerAdvice.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/PaymentController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/Payment.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/PaymentApprovalRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentApprovalResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/TossPaymentResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/exception/PaymentFailureException.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/OrderRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/PaymentRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/PaymentTypeRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/ReturnRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/PaymentService.java, src/test/resources/application-test.yml
=> [Feat] 토스 페이먼츠 연동 - #59

pom.xml, src/main/java/com/nhnacademy/heukbaekbookshop/HeukbaekbookShopApplication.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/controller/CartController.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/domain/Cart.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/domain/CartId.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/dto/CartCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/repository/CartRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/service/CartService.java, src/main/java/com/nhnacademy/heukbaekbookshop/cart/service/impl/CartServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/exception/MemberNotFoundException.java, src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/cart/service/impl/CartServiceImplTest.java
- close #109 
- 무중단 배포 설정 완료
-
=> [Feat] 무중단 배포 설정

pom.xml
- close #111 
- actuator 의존성 추가 완료
-
=> [Fix] 무중단 배포 수정

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/domain/BookCategory.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/domain/BookCategoryId.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookCategoryRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookCategoryRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookCategoryRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/impl/BookSearchServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/controller/CategoryController.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/controller/admin/CategoryAdminController.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/domain/Category.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/dto/response/CategorySummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/dto/response/SubCategorySummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/repository/CategoryRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/repository/CategoryRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/repository/impl/CategoryRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/service/CategoryService.java, src/test/java/com/nhnacademy/heukbaekbookshop/CategoryServiceTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookCategoryRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/category/repository/impl/CategoryRepositoryImplTest.java
- close #114 
- 카테고리 api 구현 완료
-
=> [Feat] 카테고리 api 작성

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookCategoryController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/domain/Book.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookViewResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookCategoryRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookCategoryRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookCategoryService.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/impl/BookSearchServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/like/LikeService.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/dto/response/SubCategorySummaryResponse.java, src/test/java/com/nhnacademy/heukbaekbookshop/LikeServiceTest.java
- close #116 
- Book 엔티티 수정 완료
-
=> [Fix] Book 엔티티 컬럼명 수정

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookCartResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookSummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookViewResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java
- close #122 
- 주문서 작성 api 구현 완료
-
=> [Feat] 주문서 작성 api 구현

src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookCategoryRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/category/repository/impl/CategoryRepositoryImplTest.java, src/test/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberServiceTest.java
=> [Test] 임시 테스트 코드 제거

src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/request/book/BookCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/request/book/BookUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookUpdateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/Order.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/Payment.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/PaymentApprovalRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/PaymentService.java
=> [FIx] 도서 dto 수정 - #133

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/repository/MemberAddressRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/service/impl/MemberAddressServiceImpl.java
=> [FIX] 회원 주소 오류 수정

src/main/java/com/nhnacademy/heukbaekbookshop/book/domain/Book.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/domain/Category.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/domain/BookCoupon.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/domain/CategoryCoupon.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/PaymentController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/RefundController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentApprovalFailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentApprovalResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/TossPaymentApprovalResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/OrderRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/PaymentService.java, src/test/java/com/nhnacademy/heukbaekbookshop/memberset/address/service/MemberAddressServiceTest.java
=> [Fix] 도서, 카테고리 쿠폰 연관관계 수정 - #139

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/dto/response/book/BookSummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/common/service/CommonService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/customer/domain/Customer.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/OrderController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/Order.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/OrderBookRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/OrderCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/OrderService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/OrderServiceImpl.java
- close #142 
- 주문 생성 api 구현 완료
-
=> [주문] 주문 작성 - 비회원

src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/DeliveryFeeController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/DeliveryFee.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/DeliveryFeeCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/DeliveryFeeUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeDeleteResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeUpdateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/exception/DeliveryFeeAlreadyExistsException.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/exception/DeliveryNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/DeliveryFeeRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/DeliveryFeeService.java
=> [Feat] 배송료 crud

src/main/java/com/nhnacademy/heukbaekbookshop/category/controller/admin/CategoryAdminController.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/service/CategoryService.java
=> [Fix] 도서 수정 폼에 카테고리 목록 안 보여지는 오류 수정 - #150

src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/PaymentController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/DeliveryFee.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/Payment.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/DeliveryFeeCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/DeliveryFeeUpdateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/PaymentApprovalRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/PaymentCancelRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeDeleteResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliveryFeeUpdateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentGatewayApprovalResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentGatewayCancelResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/DeliveryFeeService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/PaymentService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/PaymentStrategy.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/PaymentStrategyFactory.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/impl/PayPalPaymentStrategy.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/impl/TossPaymentStrategy.java
=> [Feat] 확장성 있는 결제 로직 설계

src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/domain/BookCoupon.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/domain/CategoryCoupon.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/domain/Coupon.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/mapper/CouponMapper.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/repository/CouponRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/repository/impl/CouponRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/impl/CouponServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/controller/MemberAddressController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/grade/repository/GradeRepository.java
- close #158 
-  카테고리쿠폰 수정 및 코드스멜 체크
-
=> [Fix] 카테고리쿠폰 수정 및 코드스멜 체크

src/main/java/com/nhnacademy/heukbaekbookshop/book/controller/BookCategoryController.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/exception/book/BookCategoryNotFoundException.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/BookCategoryRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookCategoryRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookCategoryService.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/impl/BookSearchServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/dto/response/ParentCategoryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/address/domain/MemberAddress.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/customer/service/CustomerService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/customer/service/impl/CustomerServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/domain/Member.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/response/MemberDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/response/MyPageResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/repository/MemberRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/repository/MemberRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/repository/impl/MemberRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/PaymentController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/OrderCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/DeliverySummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/OrderResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/OrderSummaryResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/OrderRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/impl/OrderRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/OrderService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/OrderServiceImpl.java
- close #166 
- 주문 조회 api 구현 완료 
-
=> [Feat] 주문 조회 api

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/customer/repository/CustomerRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/repository/MemberRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/OrderController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/PaymentController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/RefundController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/OrderBookRefund.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/OrderStatus.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/Refund.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/PaymentCancelRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/RefundBookRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/RefundCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/MyPageRefundDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/MyPageRefundableOrderDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentGatewayApprovalResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/PaymentGatewayCancelResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/RefundCreateResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/RefundableOrderBookResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/RefundableOrderDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/TossPaymentApprovalResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/TossPaymentCancelResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/PaymentRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/OrderService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/PaymentService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/RefundService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/OrderServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/PaymentStrategy.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/impl/PayPalPaymentStrategy.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/strategy/impl/TossPaymentStrategy.java
=> [Feat] 환불 내역 조회 및 환불 가능 주문 조회 구현

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/mapper/MemberMapper.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/request/OAuthMemberCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/MemberService.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java
- #171 
- OAuth 로그인 멤버 추가 로직 구현
-
=> [Feat] OAuth 로그인 멤버 추가 구현

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/controller/MemberController.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/request/OAuthMemberCreateRequest.java
=> [Fix] 패스워드 패턴 제거

src/main/java/com/nhnacademy/heukbaekbookshop/book/domain/document/BookDocument.java, src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/impl/BookSearchServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/image/domain/WrappingPaperImage.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/controller/WrappingPaperController.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/domain/WrappingPaper.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/response/WrappingPaperResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/WrappingPaperRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/WrappingPaperRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/repository/impl/WrappingPaperRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/WrappingPaperService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/WrappingPaperServiceImpl.java, src/test/java/com/nhnacademy/heukbaekbookshop/book/repository/book/impl/BookSearchRepositoryImplTest.java
- close #176 
- 포장지 api 구현 완료
-
=> [Feat] 포장지 api 구현

src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/controller/CouponController.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/domain/Coupon.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/mapper/CouponMapper.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/request/CouponRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/response/BookCouponResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/response/CategoryCouponResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/response/CouponPageResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/dto/response/CouponResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/repository/impl/CouponRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/impl/CouponServiceImpl.java
=> [Fix] 쿠폰 기능 로직 수정

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/response/MyPageOrderDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java
=> [Fix] 긴급 에러 수정

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/dto/response/MemberDetailResponse.java, src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/dto/request/OrderCreateRequest.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/exception/PointNotFoundException.java
- close #196 
- OrderCreateRequest 수정 완료
-
=> [Fix] 주문 생성 dto 수정

src/main/java/com/nhnacademy/heukbaekbookshop/memberset/member/service/impl/MemberServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/PaymentService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/OrderServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/event/PointUseEvent.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/event/ReviewEvent.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/listener/PointAccumulationListener.java, src/main/java/com/nhnacademy/heukbaekbookshop/review/service/ReviewService.java
- close #201
- 포인트 적립, 사용 구현
-
=> [Feat] 포인트 적립, 사용 구현

src/main/java/com/nhnacademy/heukbaekbookshop/book/service/book/BookService.java, src/main/java/com/nhnacademy/heukbaekbookshop/category/service/CategoryService.java, src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/OrderServiceImpl.java, src/test/java/com/nhnacademy/heukbaekbookshop/order/repository/DeliveryFeeRepositoryCustomTest.java, src/test/resources/com/nhnacademy/heukbaekbookshop/order/repository/deliveryFee-test.sql
- close #212 
- 배송 테스트 코드 작성 완료
-
=> [Feat] 배송 테스트 코드 작성

src/main/java/com/nhnacademy/heukbaekbookshop/order/service/impl/OrderServiceImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/event/CancelEvent.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/listener/PointAccumulationListener.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/repository/PointHistoryRepository.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/service/PointSaveService.java, src/main/java/com/nhnacademy/heukbaekbookshop/point/history/service/impl/PointSaveServiceImpl.java
=> [Feat] 주문 취소 시 포인트 회수 구현

pom.xml, src/main/java/com/nhnacademy/heukbaekbookshop/config/RedisConfig.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/impl/CouponRedisService.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/impl/CouponServiceImpl.java, src/test/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/impl/CouponRedisServiceTest.java
- #
- 쿠폰 redis에 저장, 수정, 삭제 추가
-
=> [Feat] 쿠폰 redis 저장

src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/controller/DownloadCouponController.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/repository/CouponRepositoryCustom.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/repository/impl/CouponRepositoryImpl.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/CouponService.java, src/main/java/com/nhnacademy/heukbaekbookshop/couponset/coupon/service/impl/CouponServiceImpl.java
=> [Feat] 다운로드 쿠폰 리스트 구현

src/main/java/com/nhnacademy/heukbaekbookshop/couponset/membercoupon/service/impl/CouponIssueServiceImpl.java
=> [FIX] Coupon Transactional
